# Generated by Django 5.2.2 on 2025-11-16 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutpage_contactpage_gallerypage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='media_page',
        ),
    ]
