# Generated by Django 5.2.2 on 2025-11-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_media_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='portfolio_page',
            new_name='gallery_page',
        ),
    ]
